name: Release_Build

on:
  release:
    types: [ created ] # 表示在创建新的 Release 时触发

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          company-name: Fushinn Technology
          product-name: adguard change
          file-version: ${{ github.ref_name }}
          product-version: ${{ github.ref_name }}
          standalone: true
          show-scons: true
          onefile: false
          static-libpython: yes
          lto: yes
          include-package: | 
                    logging
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: adguard_change_dns_AMD64_${{ github.ref_name }}_${{ runner.os }}-Build
          path: |
            build/app.dist/*